// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crozbkbvsrqnegoncmhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyb3pia2J2c3JxbmVnb25jbWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjkzMjEsImV4cCI6MjA2MDIwNTMyMX0.zg1C3IrVDUay0rQfzMUx7YbpB-Gq0Yk9UwTvze6uuX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);